const PROGRESS_PERCENTS = 100;
export const TIME_DURATION = 60;
export const PERCENTS_IN_SECOND = PROGRESS_PERCENTS / TIME_DURATION;
export const START_POINTS = 10;
export const ARRAY_NUM_FOR_EXTRA_POINTS = 3;
export const TRANSLATES_COMPARE_AMOUNT = 2;
